# Site settings
title: alejometal Inc.
email: alejometal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    alejometal Inc. es un blog creado por Alejandro Rodriguez en su tiempo libre.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: alejometal3
github_username:  alejor

# Build settings
markdown: kramdown
